collegemanagementmvc-master/CollegeManagement/Models/DataModel/Teacher.cs
using System.ComponentModel.DataAnnotations;

namespace CollegeManagement.Models.DataModel
{
    public class Teacher
    {

        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "First Name")]

        public string? FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string? LastName { get; set; }
      
        [Required]
        public string? Address1 { get; set; }
        [Required]
        public string? Address2 { get; set; }

        [Required]
        public string? City { get; set; }

        [Required]
        public string? State { get; set; }
        public int UserId { get; set; }
    }
}

collegemanagementmvc-master/CollegeManagement/Models/ViewModel/TeacherViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CollegeManagement.Models.ViewModel
{
    public class TeacherViewModel
    {

        public int Id { get; set; }
        [Required]
        [MaxLength(20, ErrorMessage = "FirstName cannot be exceed 20 characters")]
        [Display(Name = "Enter First Name")]
        public string? FirstName { get; set; }
        [Required]
        [Display(Name = "Enter Last Name")]
        public string? LastName { get; set; }
        [Required]
        [RegularExpression(@"^[a-z0-9](\.?[a-z0-9]){5,}@miraclesoft\.com$",
    ErrorMessage = "Please enter correct email address")]
        public string? EmailId { get; set; }

        [Required]
        [Display(Name = "Enter Permanent Address")]
        public string? Address1 { get; set; }
        [Required]
        [Display(Name = "Enter Present Address")]
        public string? Address2 { get; set; }
        [Required]
        [Display(Name = "Enter City")]
        public string? City { get; set; }
        [Required]
        [Display(Name = "Enter State")]
        public string? State { get; set; }

        public int UserId { get; set; }
    }
}

collegemanagementmvc-master/CollegeManagement/Controllers/StudentController.cs
using CollegeManagement.DataBase;
using CollegeManagement.Models.DataModel;
using CollegeManagement.Models.ViewModel;
using CollegeManagement.Service;
using Microsoft.AspNetCore.Mvc;

namespace CollegeManagement.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentservice;
        private readonly CollegeManagementContext _db;
        public StudentController(IStudentService studentService, CollegeManagementContext db)
        {
            _studentservice = studentService;
            _db = db;

        }
        public IActionResult Index()
        {
            return View("~/Views/Admin/Student/Index.cshtml");
        }
        public ActionResult Register()
        {
            return View("~/Views/Admin/Student/Register.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(StudentViewModel student)
        {
            string message = "";
            if (ModelState.IsValid)
            {
                _studentservice.Save(student);
                return RedirectToAction("Students", "Admin");

            }
            else
            {
                message = "Student Not Added";
            }
            return Content(message);



        }
        public ActionResult Status()
        {
            return View();
        }
        public ActionResult Students()
        {
            _studentservice.Details();
            ViewData.Model = _studentservice.Details();
            return View("~/views/Admin/Student/Students.cshtml");



        }
        public ActionResult StudentSearch()
        {
            return View("~/Views/Admin/Student/StudentSearch.cshtml");
        }
        [HttpGet]
        public ActionResult StudentSearch(string stdSearch)
        {
            ViewData["Getstudentdetails"] = stdSearch;

            _studentservice.GetStudent(stdSearch);
            ViewData.Model = _studentservice.GetStudent(stdSearch);
            return View("~/Views/Admin/Student/Students.cshtml");

        }

        public ActionResult Edit(int Id)
        {
            var student = _studentservice.Get(Id);
            return View("~/Views/Admin/Student/Edit.cshtml", student);
        }
        public ActionResult EditPost(Student student)
        {
            _studentservice.Edit(student);
            return RedirectToAction("Students", "Admin");

        }
        public ActionResult Delete(int Id)
        {
            _studentservice.Delete(Id);
            return RedirectToAction("Students", "Admin");
        }
        public ActionResult Student(int userid)
        {
            ViewBag.userId = TempData["user"];
            userid = ViewBag.userId;
            _studentservice.GetStudent(userid);
            ViewData["student"] = _studentservice.GetStudent(userid);
            return View("~/Views/Admin/Student/Student.cshtml");

        }
    }
}

collegemanagementmvc-master/CollegeManagement/Controllers/TeacherController.cs
using CollegeManagement.Models.DataModel;
using CollegeManagement.Models.ViewModel;
using CollegeManagement.Service;
using Microsoft.AspNetCore.Mvc;

namespace CollegeManagement.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherService _teacherservice;
        public TeacherController(ITeacherService teacherService)
        {
            _teacherservice = teacherService;
        }
        public IActionResult Index()
        {
            return View("~/Views/Admin/Teacher/Index.cshtml");
        }
        public ActionResult Register()
        {
            return View("~/Views/Admin/Teacher/Register.cshtml");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(TeacherViewModel teacher)
        {
            string message = "";
            if (ModelState.IsValid)
            {
                _teacherservice.Save(teacher);
                return RedirectToAction("Teachers");

            }
            else
            {
                message = "Teacher Not Added";
            }
            return Content(message);



        }
        public ActionResult Status()
        {
            return View();
        }
        public ActionResult Teachers()
        {
            _teacherservice.Details();
            ViewData.Model = _teacherservice.Details();
            return View("~/Views/Admin/Teacher/Teachers.cshtml");

        }
        public ActionResult Edit(int Id)
        {
            var teacher = _teacherservice.Get(Id);
            return View("~/Views/Admin/Teacher/Edit.cshtml", teacher);
        }
        public ActionResult EditPost(Teacher teacher)
        {
            var teac = _teacherservice.Edit(teacher);
            return RedirectToAction("Teachers", "Admin");

        }
        public ActionResult Delete(int Id)
        {
            _teacherservice.Delete(Id);
            return RedirectToAction("Teachers", "Admin");

        }
        public ActionResult Teacher(int userid)
        {
            ViewBag.userId = TempData["user"];
            userid = ViewBag.userId;
            _teacherservice.GetTeacher(userid);
            ViewData["student"] = _teacherservice.GetTeacher(userid);
            return View("~/Views/Admin/Teacher/Teacher.cshtml");

        }
        public ActionResult TeacherSearch()
        {
            return View("~/Views/Admin/Teacher/TeacherSearch.cshtml");
        }
        [HttpGet]
        public ActionResult TeacherSearch(string terSearch)
        {
            ViewData["GetTeacherdetails"] = terSearch;

            _teacherservice.GetTeacher(terSearch);
            ViewData.Model = _teacherservice.GetTeacher(terSearch);
            return View("~/Views/Admin/Teacher/Teachers.cshtml");

        }
    }
}

collegemanagementmvc-master/CollegeManagement/Views/Admin/Teacher/Edit.cshtml
@model CollegeManagement.Models.DataModel.Teacher;

<div class="container">
    <h2 class="text-center">Edit Details</h2>
    <br />
@*    <div class="text-right">
        <input type="button" id="btnREGISTER" value="REGISTER" Onclick="location.href = '@Url.Action("Register", "Teacher")'" />

    </div>*@
    <form method="post" >
        <div class="row">
            <div class="col-md-6">
                <input asp-for="Id" hidden/>
                <div class="form-outline">

                    <label>FirstName :</label>
                    <input asp-for="FirstName" class="form-control" placeholder="First Name" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <br />
                <div class="form-outline">
                    <label>LastName :</label>
                    <input asp-for="LastName" class="form-control" placeholder="Last Name" />
                    <span asp-validation-for="LastName" class="text-danger"></span>

                </div>
                <br />
                <div class="form-outline">
                    <label>Address1 :</label>
                    <input asp-for="Address1" class="form-control" placeholder="Address1" />
                    <span asp-validation-for="Address1" class="text-danger"></span>

                </div>
                <br />
            </div>
            <div class="col-md-6">
                <div class="form-outline">
                    <label>Address2 :</label>
                    <input asp-for="Address2" class="form-control" placeholder="Address2" />
                    <span asp-validation-for="Address2" class="text-danger"></span>

                </div>
                <br />
                <div class="form-outline">
                    <label>City :  </label>
                    <input asp-for="City" class="form-control" placeholder="City" />
                    <span asp-validation-for="City" class="text-danger"></span>

                </div>
                <br />
                <div class="form-outline">
                    <label>State :  </label>
                    <input asp-for="State" class="form-control" placeholder="State" />
                    <span asp-validation-for="State" class="text-danger"></span>

                </div>
            </div>
        </div>
        <div>

            <input type="submit" class="btn-dark" value="Save"  asp-action="EditPost" asp-controller="Teacher"/>
        </div>
    </form>

</div>

collegemanagementmvc-master/CollegeManagement/Views/Admin/Teacher/Index.cshtml
@{
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<div class="text-center">
    <h1>Registration :</h1>
        

</div>
<div class="text-right">
    <input type="button" id="btnREGISTER"  value="GetTeacherList" Onclick="location.href = '@Url.Action("Students", "Teacher")'" />
</div>

<div class="row">
    <div class="col-md-6">
        <h2> New Teacher </h2>
        <p>
            If your are new Tecaher plz Register below.
        </p>
        <input type="button" id="btnREGISTER" value="REGISTER" Onclick="location.href = '@Url.Action("Register", "Tecaher")'" />
    </div>


</div>

collegemanagementmvc-master/CollegeManagement/Views/Admin/Teacher/Register.cshtml
@model CollegeManagement.Models.ViewModel.TeacherViewModel;



<div class="container">
    <h2 class="text-center">REGISTRATION</h2>
    <br />
    <form method="post">
        <div class="row">
            <div class="col-md-6">

                <div class="form-outline">

                    <label>FirstName :</label>
                    <input asp-for="FirstName" class="form-control" placeholder="FirstName" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <br />
                <div class="form-outline">
                    <label>LastName :</label>
                    <input asp-for="LastName" class="form-control" placeholder="LastName" />
                    <span asp-validation-for="LastName" class="text-danger"></span>

                </div>
                <br />
                  <div class="form-outline">
                    <label>Email :</label>
                    <input asp-for="EmailId" class="form-control" placeholder="Email" />
                    <span asp-validation-for="EmailId" class="text-danger"></span>

                </div>
                <br />
                <div class="form-outline">
                    <label>Address1 :</label>
                    <input asp-for="Address1" class="form-control" placeholder="Address1" />
                    <span asp-validation-for="Address1" class="text-danger"></span>

                </div>

                <br />
              
                @*<br />
                    <br />
                    <div class="form-outline">
                        <label>Password :</label>
                        <input asp-for="Password" class="form-control" placeholder="Address1" />
                        <span asp-validation-for="Password" class="text-danger"></span>

                    </div>
                    <br />*@
            </div>
            <div class="col-md-6">

                <div class="form-outline">
                    <label>Address2 :</label>
                    <input asp-for="Address2" class="form-control" placeholder="Address2" />
                    <span asp-validation-for="Address2" class="text-danger"></span>

                </div>
                <br />
                <div class="form-outline">
                    <label>City :  </label>
                    <input asp-for="City" class="form-control" placeholder="City" />
                    <span asp-validation-for="City" class="text-danger"></span>

                </div>
                <br />
                <div class="form-outline">
                    <label>State :  </label>
                    <input asp-for="State" class="form-control" placeholder="State" />
                    <span asp-validation-for="State" class="text-danger"></span>

                </div>
            </div>
        </div>
        <div>

            <input type="submit" class="btn-dark" value="Submit" />
        </div>
    </form>

</div>

collegemanagementmvc-master/CollegeManagement/Views/Admin/Teacher/Teacher.cshtml
@using CollegeManagement.Models.DataModel;
@model IEnumerable<CollegeManagement.Models.DataModel.Teacher>

@{

    Layout = "~/Views/Shared/_TeacherLayout.cshtml";

    ViewBag.Title = "Teacher";


}
@{
    var data = (Teacher)ViewData["student"];
}
<div>
    <input asp-for="@data.Id" hidden />

    <input asp-for="@data.UserId" hidden />
    <table class="table">
        <thead>
            <tr>
                <th>

                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address2)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.State)

                </th>

            </tr>
        </thead>
        <tbody>

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => @data.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => @data.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => @data.Address1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => @data.Address2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => @data.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => @data.State)
                </td>

                @*<td>
                        <a asp-action="Edit" class="bg-success" asp-controller="Student" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Delete" class="bg-danger" asp-controller="Student" asp-route-id="@item.Id">Delete</a>
                    </td>*@
            </tr>

        </tbody>
    </table>
</div>

collegemanagementmvc-master/CollegeManagement/Views/Admin/Teacher/Teachers.cshtml
@using CollegeManagement.Models.DataModel;
@model IEnumerable<CollegeManagement.Models.DataModel.Teacher>

@{

    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
    ViewBag.Title = "Teachers";


}
@*<p>
    @using (Html.BeginForm("Index", "Home", FormMethod.Get))
    {
        <b>Search By:</b>
        @Html.RadioButton("searchBy","Name",true)<text>Name</text>
        @Html.TextBox("search") <input type="search" value="Submit"/>
    }
</p>*@

<div class="row">
    <div class="col-6">
        <form method="get" asp-action="TeacherSearch" asp-controller="Teacher" class="text-center">
          <p>
             <input type="search" placeholder="Enter Teacher First Name or Last Name"  value="@ViewData["GetTeacherDetails"]" name="terSearch" />
             <input type="submit" value="search" class="btn btn-primary" />
             <a asp-action="Teachers" asp-controller="Teacher" class="btn btn-success">Get all Teacher</a>
          </p>
        </form>
    </div>
    <div class="col-6">
        <div class="text-right">
            <input type="button" value="AddTecaher" class="text-end btn btn-primary" Onclick="location.href = '@Url.Action("Register", "Teacher")'" />
        </div>
    </div>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)

            </th>
         
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewData.Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
           
          <td>
                    <a asp-action="Edit" class="btn btn-warning " asp-controller="Student" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" class="btn btn-danger " asp-controller="Student" asp-route-id="@item.Id">Delete</a>
                </td>
        </tr>
        }
    </tbody>
</table>